In [1]:
from operator import countOf
from statistics import mean

from numpy.ma.core import count

import numpy as np

import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [3]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})
df3 = pd.DataFrame({'C': ['C0', 'C1'], 'D': ['D0', 'D1']})
df4 = pd.DataFrame({'B': ['B4', 'B5'], 'C': ['C4', 'C5']})

In [4]:
print(df1)
print(df2)

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3

In [7]:
result = pd.concat([df1, df2], ignore_index=True)

In [8]:
print(result)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [11]:
tagged_result = pd.concat([df1, df2], keys=['Batch_1', 'Batch_2'])
print(tagged_result)

            A   B
Batch_1 0  A0  B0
        1  A1  B1
Batch_2 0  A2  B2
        1  A3  B3

In [13]:
inner_result = pd.concat([df1, df4], join='inner', ignore_index=True)
print(inner_result)

     A   B    C
0   A0  B0  NaN
1   A1  B1  NaN
2  NaN  B4   C4
3  NaN  B5   C5

In [15]:
result_horizontal = pd.concat([df1, df3], axis=1)
print(result_horizontal)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [16]:
result_horizontal = pd.concat([df1, df3], join='inner', axis=1)
print(result_horizontal)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

In [21]:
pd.read_csv("sales_data.csv")

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [22]:
data = pd.read_csv("sales_data.csv")

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   str
 2   Sales_Rep             1000 non-null   str
 3   Region                1000 non-null   str
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   str
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   str
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   str
 12  Sales_Channel         1000 non-null   str
 13  Region_and_Sales_Rep  1000 non-null   str
dtypes: float64(4), int64(2), str(8)
memory usage: 109.5 KB

In [24]:
data.head(10)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie

In [26]:
df = pd.DataFrame(data)

In [35]:
df.groupby('Sales_Rep')['Sales_Amount'].sum().sort_values()

Sales_Rep
Charlie     860811.48
Alice       965541.77
Eve         970183.99
Bob        1080990.63
David      1141737.36
Name: Sales_Amount, dtype: float64

In [34]:
df.groupby('Sales_Rep')['Quantity_Sold'].sum().sort_values()

Sales_Rep
Charlie    4217
Alice      4832
Bob        4977
Eve        5287
David      6042
Name: Quantity_Sold, dtype: int64

In [41]:
df.groupby(['Sales_Rep','Product_Category'])['Sales_Amount'].sum().sort_values()

Sales_Rep  Product_Category
Charlie    Food                182441.71
Eve        Food                197852.62
Charlie    Electronics         214363.09
           Furniture           220677.01
Alice      Food                226832.16
Eve        Furniture           232845.49
Alice      Clothing            235269.91
David      Electronics         240443.36
Alice      Furniture           241123.41
Charlie    Clothing            243329.67
Bob        Electronics         248596.34
           Clothing            254984.62
Eve        Clothing            261705.32
Alice      Electronics         262316.29
Bob        Furniture           264421.15
Eve        Electronics         277780.56
David      Food                281658.53
           Furniture           301450.63
Bob        Food                312988.52
David      Clothing            318184.84
Name: Sales_Amount, dtype: float64

In [42]:
df.pivot_table(index='Sales_Rep', columns='Quantity_Sold', values='Sales_Amount', aggfunc=sum)

Quantity_Sold,1,2,3,4,5,6,7,8,9,10,...,40,41,42,43,44,45,46,47,48,49
Sales_Rep,,,,,,,,,,,,,,,,,,,,,
Alice,22626.58,45452.78,11225.19,11958.99,7844.10,29876.36,9739.68,10788.59,7149.85,4710.32,...,1103.59,6261.90,18305.34,37463.49,15183.59,8073.47,3391.32,24465.34,28068.39,18238.99
Bob,21746.95,20829.67,28469.95,41527.60,8568.51,5235.14,22602.77,14985.44,15763.39,16797.60,...,21158.84,7277.56,13555.33,18372.34,2089.52,34732.35,32146.03,24312.20,8171.78,16881.36
Charlie,8063.70,17051.85,25133.07,37703.08,16065.13,9722.70,26466.93,12148.61,8954.61,33875.78,...,24313.38,20913.84,17436.83,6888.75,27553.67,25943.44,13049.42,22248.93,22696.06,NaN
David,26063.59,17139.73,4155.74,11027.63,8933.56,29386.03,25553.82,34276.73,26344.29,25094.58,...,26765.41,11735.48,57774.46,16425.00,20957.74,57122.08,26428.46,50126.82,18943.68,16367.43
Eve,17507.05,8217.13,4127.37,12227.55,27855.39,20692.88,5739.59,14081.75,25995.64,7412.11,...,31826.51,4916.65,22800.72,28979.25,6961.88,8992.24,25391.26,30916.40,4166.92,21207.23

Sales Rep Ranking by Sales Amount & Quantity Sold Columns

In [44]:
df.pivot_table(index='Region', columns='Sales_Rep', values='Sales_Amount', aggfunc=sum)

Sales_Rep      Alice        Bob    Charlie      David        Eve
Region
East       260789.47  309876.11  165172.94  284613.51  239340.90
North      249647.22  233464.81  299789.01  282539.27  304172.20
South      239414.54  251200.43  156140.68  311416.99  196078.22
West       215690.54  286449.28  239708.85  263167.59  230592.67

In [46]:
df.groupby(['Sales_Rep','Region'])['Sales_Amount'].sum().sort_values()

Sales_Rep  Region
Charlie    South     156140.68
           East      165172.94
Eve        South     196078.22
Alice      West      215690.54
Eve        West      230592.67
Bob        North     233464.81
Eve        East      239340.90
Alice      South     239414.54
Charlie    West      239708.85
Alice      North     249647.22
Bob        South     251200.43
Alice      East      260789.47
David      West      263167.59
           North     282539.27
           East      284613.51
Bob        West      286449.28
Charlie    North     299789.01
Eve        North     304172.20
Bob        East      309876.11
David      South     311416.99
Name: Sales_Amount, dtype: float64

In [48]:
df.groupby('Region')['Discount'].sum().sort_values()

Region
South    33.52
West     36.19
North    39.93
East     42.75
Name: Discount, dtype: float64

In [49]:
df.groupby('Sales_Channel')['Discount'].sum().sort_values()

Sales_Channel
Online    74.45
Retail    77.94
Name: Discount, dtype: float64

In [50]:
df.groupby('Sales_Rep')['Discount'].sum().sort_values()

Sales_Rep
Charlie    26.22
Alice      27.09
Bob        29.62
Eve        32.92
David      36.54
Name: Discount, dtype: float64

In [52]:
df.groupby('Region').agg({'Discount': ['sum', 'count', 'mean', 'min', 'max']})

       Discount
            sum count      mean  min  max
Region
East      42.75   263  0.162548  0.0  0.3
North     39.93   267  0.149551  0.0  0.3
South     33.52   226  0.148319  0.0  0.3
West      36.19   244  0.148320  0.0  0.3

In [56]:
df.groupby('Region').agg({'Discount': ['count', 'sum', 'mean', 'min', 'max'],
                          'Sales_Amount': ['sum', 'median']})

       Discount                            Sales_Amount
          count    sum      mean  min  max          sum    median
Region
East        263  42.75  0.162548  0.0  0.3   1259792.93  4649.880
North       267  39.93  0.149551  0.0  0.3   1369612.51  5207.030
South       226  33.52  0.148319  0.0  0.3   1154250.86  4759.875
West        244  36.19  0.148320  0.0  0.3   1235608.93  5249.625

In [58]:
df.pivot_table(index='Region', columns='Sales_Rep', values=['Sales_Amount', 'Discount'], aggfunc=sum)

          Discount                           Sales_Amount             \
Sales_Rep    Alice   Bob Charlie David   Eve        Alice        Bob
Region
East          8.45  9.81    6.21  9.79  8.49    260789.47  309876.11
North         6.13  7.46    8.12  8.36  9.86    249647.22  233464.81
South         6.30  5.74    5.06  9.82  6.60    239414.54  251200.43
West          6.21  6.61    6.83  8.57  7.97    215690.54  286449.28


Sales_Rep    Charlie      David        Eve
Region
East       165172.94  284613.51  239340.90
North      299789.01  282539.27  304172.20
South      156140.68  311416.99  196078.22
West       239708.85  263167.59  230592.67

In [69]:
df.pivot_table(index='Product_Category', columns='Payment_Method', values=['Sales_Amount', 'Discount'], aggfunc=['sum', 'mean'])

                           sum                                              \
                      Discount                     Sales_Amount
Payment_Method   Bank Transfer   Cash Credit Card Bank Transfer       Cash
Product_Category
Clothing                 16.22  12.37       14.35     459052.96  381696.31
Electronics              10.33   9.92       13.33     430362.41  332483.20
Food                     11.88  12.04       10.84     453788.68  381600.46
Furniture                14.07  13.16       13.88     374159.12  448558.57

                                      mean                        \
                                  Discount
Payment_Method   Credit Card Bank Transfer      Cash Credit Card
Product_Category
Clothing           472725.09      0.174409  0.158590    0.147938
Electronics        480654.03      0.130759  0.141714    0.137423
Food               366384.40      0.150380  0.154359    0.157101
Furniture          437800.00      0.154615  0.151264    0.169268


                  Sales_Amount
Payment_Method   Bank Transfer         Cash  Credit Card
Product_Category
Clothing           4936.053333  4893.542436  4873.454536
Electronics        5447.625443  4749.760000  4955.196186
Food               5744.160506  4892.313590  5309.918841
Furniture          4111.638681  5155.845632  5339.024390

In [60]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='str')

In [70]:
df.pivot_table(index='Product_Category', columns='Payment_Method', values=['Sales_Amount', 'Discount'], aggfunc={"Sales_Amount":'sum', "Discount":'count'})

                      Discount                   Sales_Amount             \
Payment_Method   Bank Transfer Cash Credit Card Bank Transfer       Cash
Product_Category
Clothing                    93   78          97     459052.96  381696.31
Electronics                 79   70          97     430362.41  332483.20
Food                        79   78          69     453788.68  381600.46
Furniture                   91   87          82     374159.12  448558.57


Payment_Method   Credit Card
Product_Category
Clothing           472725.09
Electronics        480654.03
Food               366384.40
Furniture          437800.00